# POSTTEST 7
## Kecerdasan Buatan
ALFI NOR IHSAN

2109106018

A1-21

Dataset yang digunakan : [Airline_Passenger_Satisfaction](https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction)

Instruksi :
- Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.
- Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.
- Tampilkan dimensi dari kedua variable tersebut.
- Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).
- Tampilkan nilai maksimum dan minimum dari variable random_tensor.
- Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation).
- Tampilkan hasil sorting dari kedua variable di atas (descending).

## Deklarasi Variabel 

In [137]:
import tensorflow as tf

## Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [138]:
random_tensor = tf.random.normal((5,5),
mean = 5,
stddev = 1,
seed = 1)

print(random_tensor)

tf.Tensor(
[[4.9339705 4.8576202 4.656832  5.506004  4.388333 ]
 [4.9826694 5.158624  3.9325118 5.0596547 4.5669565]
 [5.7648673 5.095687  7.7204247 6.185311  4.031162 ]
 [3.9772263 4.2564864 4.3147125 4.9423876 3.8767166]
 [4.961233  7.3493233 5.2404213 4.4452205 3.0373416]], shape=(5, 5), dtype=float32)


## Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [139]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],
shape = (5,5), 
dtype = tf.float32)

## Menampilkan dimensi dari variabel random_tensor dan prime_tensor

### random_tensor

In [140]:
print('Dimensi variabel random_tensor : ',
random_tensor.shape)

Dimensi variabel Random_Tensor :  (5, 5)


### prime_tensor

In [141]:
print('Dimensi variabel prime_tensor : ',
prime_tensor.shape)

Dimensi variabel Prime_Tensor :  (5, 5)


## Menampilkan hasil dari perhitungan aritmetika dari variabel random_tensor dan prime_tensor

### Penjumlahan

In [142]:
print("Penjumlahan :\n" ,
tf.add(random_tensor,prime_tensor).numpy())

Penjumlahan :
 [[  6.9339705   7.8576202   9.656832   12.506004   15.388332 ]
 [ 17.98267    22.158625   22.932512   28.059654   33.566956 ]
 [ 36.764866   42.095688   48.720425   49.18531    51.031162 ]
 [ 56.977226   63.256485   65.31471    75.94239    76.87672  ]
 [ 83.961235   90.34932    94.24042   101.44522   104.03734  ]]


### Pengurangan

In [143]:
print("Pengurangan :\n" ,
tf.subtract(random_tensor,prime_tensor).numpy())

Pengurangan :
 [[  2.9339705    1.8576202   -0.34316778  -1.4939961   -6.611667  ]
 [ -8.01733    -11.841375   -15.067488   -17.940346   -24.433044  ]
 [-25.235132   -31.904312   -33.279575   -36.81469    -42.968838  ]
 [-49.022774   -54.743515   -56.685287   -66.05761    -69.12328   ]
 [-74.038765   -75.65068    -83.75958    -92.55478    -97.96266   ]]


### Perkalian

In [144]:
print("Perkalian :\n" ,
tf.multiply(random_tensor,prime_tensor).numpy())

Perkalian :
 [[  9.867941  14.572861  23.28416   38.542027  48.27166 ]
 [ 64.774704  87.69661   74.71773  116.372055 132.44174 ]
 [178.71089  188.54042  316.5374   265.96835  189.4646  ]
 [210.793    251.1327   263.19745  350.90952  283.0003  ]
 [391.9374   609.99384  466.3975   431.18637  306.7715  ]]


### Pembagian

In [145]:
print("Pembagian :\n" ,
tf.divide(random_tensor,prime_tensor).numpy())

Pembagian :
 [[2.4669852  1.6192068  0.93136644 0.786572   0.39893934]
 [0.38328224 0.30344847 0.20697431 0.219985   0.15748125]
 [0.18596347 0.13772127 0.18830304 0.14384444 0.0857694 ]
 [0.075042   0.07214384 0.070733   0.06961109 0.05310571]
 [0.06280042 0.08854606 0.05888114 0.04582702 0.03007269]]


### Perpangkatan

In [146]:
print("Perpangkatan :\n" ,
tf.pow(prime_tensor,random_tensor).numpy())

Perpangkatan :
 [[3.05684280e+01 2.07813553e+02 1.79881311e+03 4.49896953e+04
  3.71516172e+04]
 [3.55149656e+05 2.22547925e+06 1.06835016e+05 7.76019550e+06
  4.77208400e+06]
 [3.95824128e+08 9.79636560e+07 2.82732842e+12 1.26914181e+10
  5.50170100e+06]
 [7.20834000e+06 3.44831960e+07 5.04876320e+07 1.41135501e+09
  1.67330340e+07]
 [2.59758874e+09 1.27035553e+14 1.64295209e+10 6.78638336e+08
  1.22407688e+06]]


### Perkalian Matrix

In [147]:
print("Perkalian Matrix:\n" ,
tf.matmul(random_tensor,prime_tensor).numpy())

Perkalian Matrix:
 [[ 855.8753   958.7701  1034.3226  1163.1014  1259.1757 ]
 [ 827.8866   925.72455  999.25824 1124.8553  1219.8549 ]
 [ 963.3901  1089.0968  1178.2572  1319.7129  1432.7235 ]
 [ 765.252    857.3046   924.17596 1038.2235  1122.3218 ]
 [ 743.4634   848.08514  920.7825  1039.334   1145.2764 ]]


## Menampilkan nilai maksimum dan minimum dari variable random_tensor

### Nilai maksimal

In [148]:

print("Nilai maksimal variabel random_tensor : ", 
tf.reduce_max(random_tensor).numpy())

Nilai maksimal variabel random_tensor :  7.7204247


### Nilai minimal

In [149]:
print("Nilai minimal variabel random_tensor : ", 
tf.reduce_min(random_tensor).numpy())

Nilai minimal variabel random_tensor :  3.0373416


## Menggabungkan variabel random_tensor dan prime_tensor dengan metode concatenation

In [150]:
concatenation =tf.concat([random_tensor,prime_tensor],axis=1)
concatenation.numpy()

array([[  4.9339705,   4.8576202,   4.656832 ,   5.506004 ,   4.388333 ,
          2.       ,   3.       ,   5.       ,   7.       ,  11.       ],
       [  4.9826694,   5.158624 ,   3.9325118,   5.0596547,   4.5669565,
         13.       ,  17.       ,  19.       ,  23.       ,  29.       ],
       [  5.7648673,   5.095687 ,   7.7204247,   6.185311 ,   4.031162 ,
         31.       ,  37.       ,  41.       ,  43.       ,  47.       ],
       [  3.9772263,   4.2564864,   4.3147125,   4.9423876,   3.8767166,
         53.       ,  59.       ,  61.       ,  71.       ,  73.       ],
       [  4.961233 ,   7.3493233,   5.2404213,   4.4452205,   3.0373416,
         79.       ,  83.       ,  89.       ,  97.       , 101.       ]],
      dtype=float32)

## Menampilkan hasil sorting dari penggabungan variable random_tensor dengan prime_tensor (concatenation), serta menampilkan hasil sorting dari dua variabel secara descending

In [151]:

print("Sorting Concatenation :\n",
tf.sort(concatenation, direction = "DESCENDING").numpy())

Sorting Concatenation :
 [[ 11.          7.          5.506004    5.          4.9339705   4.8576202
    4.656832    4.388333    3.          2.       ]
 [ 29.         23.         19.         17.         13.          5.158624
    5.0596547   4.9826694   4.5669565   3.9325118]
 [ 47.         43.         41.         37.         31.          7.7204247
    6.185311    5.7648673   5.095687    4.031162 ]
 [ 73.         71.         61.         59.         53.          4.9423876
    4.3147125   4.2564864   3.9772263   3.8767166]
 [101.         97.         89.         83.         79.          7.3493233
    5.2404213   4.961233    4.4452205   3.0373416]]


In [152]:
print("Sorting random_tensor :\n",
tf.sort(random_tensor,direction = "DESCENDING").numpy())

Sorting random_tensor :
 [[5.506004  4.9339705 4.8576202 4.656832  4.388333 ]
 [5.158624  5.0596547 4.9826694 4.5669565 3.9325118]
 [7.7204247 6.185311  5.7648673 5.095687  4.031162 ]
 [4.9423876 4.3147125 4.2564864 3.9772263 3.8767166]
 [7.3493233 5.2404213 4.961233  4.4452205 3.0373416]]


In [153]:
print("Sorting random_tensor :\n",
tf.sort(prime_tensor,direction = "DESCENDING").numpy())

Sorting random_tensor :
 [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]
